ignore:
  - "box/"                      # packaging related
  - "response/"                 # responder
  - "app/backend_mocks.go"      # mainly interfaces and mocks
  - "apptest/"                  # unified testing kit